# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.0"
before_install:
  - export M2_HOME=$HOME/apache-maven-3.5.0
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Swagger")'
  - ./plugin/build.sh
  - julia -e 'using Pkg; Pkg.test("Swagger"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Swagger")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Swagger")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
